export const toyota = {
  modelLine: [
    "Toyota Land Cruiser J100J105",
    "Toyota Land Cruiser Prado J120",

    "Manual Belts w2 Airbags and Side Curtain Airbags",
    "Manual Belt 1 STD North America No Airbags International",
    "Manual Belts w2 Airbags North America 1 Airbag Driver Seat International",
    "Manual Belts w2 Airbags North America 2 Front Airbags International",
    "Manual Belts w2 Airbags Side Airbags Side Curtain Shield Airbags and Knee Airbag Driver Seat",
    "Manual Belts w2 Airbags and Knee Airbag Driver Seat",
    "Manual Belts w2 Airbags and Side Airbags",
    "Manual Belts w2 Airbags Side Airbags and Front Curtain Airbags",
    "Manual Belts w2 Airbags Side Airbags Three-Row Curtain Shield Airbags and Knee Airbag",
    "Manual Belts w2 Airbags Side Airbags and Knee Airbag",

    "MR2  MR2 Spyder",
    "Tundra  Tundra",
    "Echo  Yaris Verso",
    "Yaris  Scion xA  Scion xB  Scion xD  Urban Cruiser",
    "Hilux",
    "Scion tC",
    "Highlander  Sequoia  Celica RWD  Supra",
    "Avalon  Avensis Verso  Ipsum",
    "Sienna  Previa  Aygo",
    "T100",
    "Corolla  Matrix  Auris",
    "FJ Cruiser",
    "Hilux  Fortuner",
    "Highlander",
    "Land Cruiser  Land Cruiser Prado",
    "Camry  Aurion TRD",
    "Tercel  Paseo  Avensis",
    "Previa",
    "Tacoma and older trucks as well",
    "Camry Solara",
    "4Runner  Corolla Verso",
    "Fortuner",
    "Celica FWD",
    "Prius",
    "RAV4",
    "MR2 non-spyder models",
    "Cressida",
  ],
  modelYear: [
    "1990",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
    "2006",
    "2007",
    "2008",
    "2009",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
  ],
};
